"""Search synonyms for the segment library, per preset id and per language.

These are the EXTRA words the search box matches on top of a preset's label and
its cloud-model prompt token: a synonym, a plural, a regional word, or the same
word without its accents (the search compares folded text, so both spellings
earn their place). They are not translations of the label, which is indexed
already: they are what a user types when the label is not the word they know.

The table covers the twelve catalogue languages. It is mirrored on the server
side in ``src/lib/ai-segmentation/presets.ts`` (``PRESET_SEARCH_TERMS``) and
must keep the same shape there, since the served catalogue overrides this one.
Optional by design: a preset with no row gets an empty dict, and a catalogue
payload without the field still searches on label + prompt.
"""

from __future__ import annotations

_SEARCH_TERMS: dict[str, dict[str, str]] = {
    "building": {"en": "structure footprint block outline", "fr": "immeuble construction emprise batiment bati",
                 "es": "inmueble construccion edificacion huella", "pt": "imovel construcao edificacao",
                 "de": "bauwerk gebäude grundriss gebäudeumriss block", "it": "edificio struttura impronta sagoma",
                 "nl": "gebouw bebouwing pand omtrek contour", "pl": "budynek obrys budynku zabudowa konstrukcja",
                 "id": "bangunan struktur tapak gedung konstruksi", "ja": "建物 建築物 建物輪郭 建物フットプリント",
                 "zh_CN": "建筑物 建筑 轮廓 建筑占地", "zh_TW": "建築物 建物 建築輪廓 建物外框 建築占地"},
    "rooftop": {"en": "roof roofs tiles roof outline", "fr": "toit toits toiture couverture",
                "es": "techo techos cubierta azotea", "pt": "telhado telhados cobertura laje",
                "de": "dach dächer dachziegel dachfläche dachumriss", "it": "tetto tetti tegole sagoma del tetto",
                "nl": "dak daken dakpannen dakrand dakcontour", "pl": "dach dachy pokrycie dachowe obrys dachu",
                "id": "atap genteng permukaan atap garis atap", "ja": "屋根 屋上 瓦屋根 屋根形状 屋根輪郭",
                "zh_CN": "屋顶 房顶 瓦顶 屋顶轮廓", "zh_TW": "屋頂 房頂 屋面 瓦頂 屋頂輪廓"},
    "house": {"en": "home dwelling residential villa", "fr": "maison pavillon habitation villa",
              "es": "vivienda chalet casas residencial", "pt": "moradia residencia casas",
              "de": "haus wohnhaus wohngebäude villa", "it": "casa abitazione residenza villa",
              "nl": "huis woning woonhuis villa", "pl": "dom budynek mieszkalny willa siedlisko",
              "id": "rumah hunian tempat tinggal vila", "ja": "家 住宅 一戸建て 民家 邸宅",
              "zh_CN": "房屋 住宅 民居 别墅", "zh_TW": "房屋 住宅 民宅 住家 別墅"},
    "warehouse": {"en": "depot logistics hangar industrial building", "fr": "entrepot hangar logistique depot",
                  "es": "nave industrial bodega deposito almacen", "pt": "armazem galpao deposito logistica",
                  "de": "lager lagerhalle logistikhalle hangar industriegebäude",
                  "it": "magazzino deposito hangar edificio industriale",
                  "nl": "magazijn loods distributiecentrum opslagloods bedrijfspand",
                  "pl": "magazyn skład hala magazynowa centrum logistyczne",
                  "id": "gudang depo logistik hanggar bangunan industri", "ja": "倉庫 物流施設 格納庫 工場建物 貨物庫",
                  "zh_CN": "仓库 物流仓 储运仓 工业建筑", "zh_TW": "倉庫 貨倉 物流中心 機庫 工業建築"},
    "greenhouse": {"en": "glasshouse polytunnel nursery", "fr": "serre serres tunnel horticulture",
                   "es": "invernaderos umbraculo vivero", "pt": "estufa estufas viveiro",
                   "de": "gewächshaus glashaus folientunnel baumschule", "it": "serra tunnel vivaio serra per piante",
                   "nl": "kas kassen glastuinbouw tunnelkas kwekerij",
                   "pl": "szklarnia tunel foliowy inspekt ogrodniczy",
                   "id": "rumah kaca polytunnel pembibitan persemaian",
                   "ja": "温室 ビニールハウス ガラス温室 園芸施設 育苗施設", "zh_CN": "温室 大棚 玻璃温室 育苗棚",
                   "zh_TW": "溫室 玻璃溫室 塑膠溫室 育苗棚 園藝溫室"},
    "shed": {"en": "outbuilding hut barn garage", "fr": "abri remise grange garage",
             "es": "caseta cobertizo granero garaje", "pt": "barracao abrigo celeiro garagem",
             "de": "schuppen nebengebäude hütte scheune garage", "it": "capanno baracca fienile garage",
             "nl": "schuur tuinhuis berging loods garage", "pl": "szopa budynek gospodarczy komórka garaż stodoła",
             "id": "gudang kecil gubuk lumbung garasi", "ja": "物置 小屋 納屋 倉庫 ガレージ",
             "zh_CN": "棚屋 小屋 谷仓 车库", "zh_TW": "棚屋 雜物房 小屋 穀倉 車庫"},
    "silo": {"en": "grain silo granary farm silo", "fr": "silos grenier", "es": "silos granero", "pt": "silos celeiro",
             "de": "silo getreidesilo speicher landwirtschaftssilo", "it": "silo cereali granaio silos agricolo",
             "nl": "silo graansilo graanopslag landbouwsilo opslagtank",
             "pl": "silos elewator spichlerz zbiornik zbożowy", "id": "silo biji-bijian lumbung penyimpanan hasil tani",
             "ja": "サイロ 穀物サイロ 貯蔵庫 農業サイロ 飼料サイロ", "zh_CN": "筒仓 粮仓 农业筒仓 储粮仓",
             "zh_TW": "筒倉 穀倉 農用筒倉 儲糧塔 儲料筒倉"},
    "storage_tank": {"en": "tank oil tank fuel tank cistern", "fr": "cuve citerne reservoir",
                     "es": "tanque cisterna deposito", "pt": "tanque cisterna reservatorio",
                     "de": "tank öltank kraftstofftank zisterne speichertank",
                     "it": "serbatoio cisterna vasca serbatoio olio",
                     "nl": "tank olietank brandstoftank waterreservoir opslagtank",
                     "pl": "zbiornik zbiornik paliwa zbiornik oleju cysterna",
                     "id": "tangki tangki minyak tangki bahan bakar tandon",
                     "ja": "タンク 油槽 燃料タンク 貯水槽 貯蔵槽", "zh_CN": "储罐 油罐 燃料罐 水箱",
                     "zh_TW": "儲槽 油槽 燃料槽 水槽 儲水槽"},
    "tree": {"en": "trees canopy crown forest woodland", "fr": "arbres houppier canopee foret forêt",
             "es": "arboles copa dosel bosque", "pt": "arvores copa dossel floresta",
             "de": "bäume baumkrone kronendach wald gehölz", "it": "alberi chioma corona bosco foresta",
             "nl": "boom bomen kruin kroon bos bosgebied", "pl": "drzewo drzewa korona drzew las zagajnik",
             "id": "pohon pepohonan tajuk mahkota hutan", "ja": "木 樹木 樹冠 林 森林", "zh_CN": "树木 树冠 林地 森林",
             "zh_TW": "樹木 樹冠 林木 森林 林地"},
    "tree_canopy": {"en": "forest woodland woods canopy cover tree cover crown",
                    "fr": "foret bois couvert arbore boisement massif",
                    "es": "bosque arbolado masa forestal cubierta arborea",
                    "pt": "floresta mata bosque cobertura arborea",
                    "de": "wald gehölz wälder kronendach baumbestand baumkronen",
                    "it": "chioma arborea copertura forestale bosco vegetazione arborea corona alberi",
                    "nl": "bos bosgebied bomen kroon bladerdek boomkruinen",
                    "pl": "korona drzew zadrzewienie las kompleks leśny pokrywa koron",
                    "id": "tajuk pohon tutupan hutan kanopi pepohonan", "ja": "森林 林地 雑木林 樹冠 植生被覆 樹木被覆",
                    "zh_CN": "森林 林地 树林 林冠覆盖 树冠覆盖", "zh_TW": "森林 林地 樹林 樹冠覆蓋 樹木覆蓋 林冠"},
    "bush": {"en": "shrub scrub brush bushes", "fr": "arbuste broussaille fourre", "es": "matorral arbustos maleza",
             "pt": "arbustos moita mato", "de": "strauch gebüsch busch sträucher unterholz",
             "it": "arbusto macchia cespuglio cespugli", "nl": "struik struiken struweel kreupelhout bosjes",
             "pl": "krzew krzewy zarośla chaszcze zakrzaczenia", "id": "semak belukar perdu rimbunan",
             "ja": "低木 茂み 藪 ブラッシュ 植え込み", "zh_CN": "灌木 灌丛 灌木丛 荒草",
             "zh_TW": "灌木 灌叢 灌木叢 草叢 矮樹"},
    "grass": {"en": "lawn turf meadow pasture grassland green space",
              "fr": "pelouse gazon prairie paturage espace vert", "es": "cesped pasto pradera prado zona verde",
              "pt": "gramado relva pasto pastagem area verde", "de": "rasen grünfläche wiese weide grasland",
              "it": "prato erba tappeto erboso pascolo prateria area verde",
              "nl": "gras gazon grasveld weide weiland grasland groenstrook",
              "pl": "trawnik murawa łąka pastwisko trawy teren zielony",
              "id": "rumput halaman padang rumput padang penggembalaan lahan hijau",
              "ja": "芝生 芝 草地 牧草地 草原 緑地", "zh_CN": "草坪 草地 牧草地 牧场 草场 绿地",
              "zh_TW": "草地 草坪 草皮 牧草地 草原 綠地"},
    "vegetation": {"en": "vegetated green cover greenery plants undergrowth scrub",
                   "fr": "vegetal couvert vegetal verdure plantes broussaille",
                   "es": "cubierta vegetal verde plantas maleza", "pt": "cobertura vegetal verde plantas mato",
                   "de": "vegetation grünbewuchs begrünt pflanzen unterwuchs gebüsch",
                   "it": "vegetazione copertura verde piante sottobosco macchia arbusti",
                   "nl": "begroeiing vegetatie groen groenvoorziening planten ondergroei struweel",
                   "pl": "roślinność zieleń pokrywa roślinna rośliny podszyt zarośla",
                   "id": "vegetasi tutupan hijau tanaman semak tumbuhan bawah", "ja": "植生 緑地 緑被 植物 下草 藪",
                   "zh_CN": "植被 绿化 植物 覆盖 下层植被 灌丛", "zh_TW": "植被 綠色覆蓋 綠化 植物 下層植被 灌叢"},
    "road": {"en": "street highway motorway asphalt pavement", "fr": "rue chaussee autoroute voirie bitume",
             "es": "calle via autopista pavimento asfalto", "pt": "rua via rodovia asfalto pavimento",
             "de": "straße fahrbahn landstraße autobahn asphalt verkehrsweg",
             "it": "strada via autostrada superstrada asfalto carreggiata",
             "nl": "weg straat snelweg autoweg asfalt rijbaan",
             "pl": "droga ulica szosa autostrada nawierzchnia asfaltowa jezdnia",
             "id": "jalan ruas jalan jalan raya aspal perkerasan", "ja": "道路 通り 幹線道路 高速道路 舗装路 車道",
             "zh_CN": "道路 街道 公路 高速公路 沥青路 路面", "zh_TW": "道路 街道 公路 高速公路 柏油路 路面"},
    "parking_lot": {"en": "car park parking parking space", "fr": "stationnement aire de stationnement places",
                    "es": "aparcamiento playa de estacionamiento", "pt": "estacionamento vaga patio",
                    "de": "parkplatz stellplätze parkfläche parken autoabstellplatz",
                    "it": "parcheggio area di sosta stalli auto",
                    "nl": "parkeerplaats parkeerterrein parking parkeervak autoparkeerplaats",
                    "pl": "parking plac parkingowy miejsce parkingowe parking samochodowy",
                    "id": "parkiran tempat parkir lahan parkir area parkir",
                    "ja": "駐車場 パーキング 駐車スペース 車置き場", "zh_CN": "停车场 停车区 停车位 车辆停放区",
                    "zh_TW": "停車場 停車區 停車位 汽車停放區"},
    "bridge": {"en": "viaduct overpass flyover footbridge", "fr": "viaduc passerelle ouvrage d'art",
               "es": "viaducto paso elevado pasarela", "pt": "viaduto passarela",
               "de": "brücke viadukt überführung überquerung fußgängerbrücke",
               "it": "ponte viadotto cavalcavia sovrappasso passerella",
               "nl": "brug viaduct fly over voetbrug verkeersbrug",
               "pl": "most wiadukt estakada kładka przejazd nadziemny",
               "id": "jembatan viaduk jalan layang penyeberangan", "ja": "橋 高架橋 陸橋 立体交差 歩道橋",
               "zh_CN": "桥梁 高架桥 立交桥 人行桥", "zh_TW": "橋樑 高架橋 立交橋 跨橋 人行橋"},
    "roundabout": {"en": "traffic circle rotary junction", "fr": "giratoire carrefour rond point",
                   "es": "glorieta redondel", "pt": "rotula retorno",
                   "de": "kreisverkehr verkehrskreisel kreisförmige kreuzung",
                   "it": "rotonda rotatoria rondò incrocio circolare",
                   "nl": "rotonde verkeersplein verkeerscirkel kruispunt",
                   "pl": "rondo skrzyżowanie okrężne rondo drogowe wyspa centralna",
                   "id": "bundaran lingkaran lalu lintas simpang melingkar",
                   "ja": "ラウンドアバウト ロータリー 環状交差点 円形交差点", "zh_CN": "环岛 环形交叉口 转盘式路口",
                   "zh_TW": "圓環 環島 迴轉道 環形路口"},
    "sidewalk": {"en": "pavement footpath walkway path pedestrian", "fr": "trottoirs chemin pieton allee",
                 "es": "aceras banqueta senda peatonal", "pt": "calcadas passeio caminho pedestre",
                 "de": "gehweg fußweg bürgersteig gehsteig fußgängerweg",
                 "it": "marciapiede percorso pedonale sentiero camminamento pista pedonale",
                 "nl": "stoep trottoir voetpad wandelpad wandelroute voetgangerspad",
                 "pl": "chodnik ciąg pieszy ścieżka promenada trakt pieszy",
                 "id": "trotoar jalur pejalan kaki jalan setapak pedestrian",
                 "ja": "歩道 歩行者道 遊歩道 通路 ペデストリアン", "zh_CN": "人行道 步道 便道 走道 行人道",
                 "zh_TW": "人行道 步道 行人道 走道 側道"},
    "runway": {"en": "airstrip taxiway apron airport", "fr": "aerodrome aeroport taxiway",
               "es": "pista de aterrizaje aeropuerto", "pt": "pista de pouso aeroporto",
               "de": "startbahn landebahn flugpiste rollbahn vorfeld flughafen",
               "it": "pista pista di decollo pista aeroportuale taxiway aeroporto",
               "nl": "startbaan landingsbaan vliegstrip taxibaan platform vliegveld",
               "pl": "pas startowy lotnisko droga kołowania płyta lotniskowa",
               "id": "landasan pacu lapangan terbang taxiway apron", "ja": "滑走路 飛行場 誘導路 エプロン 空港",
               "zh_CN": "跑道 机场跑道 飞机跑道 滑行道 停机坪", "zh_TW": "跑道 飛機跑道 滑行道 停機坪 機場"},
    "dock": {"en": "quay wharf pier jetty marina port harbour harbor", "fr": "quai ponton jetee port marina",
             "es": "muelle embarcadero dique puerto", "pt": "cais pier atracadouro porto",
             "de": "kai anlegestelle pier steg marina hafen", "it": "molo banchina pontile darsena porto marina",
             "nl": "kade aanlegsteiger pier steiger jachthaven haven",
             "pl": "nabrzeże keja pomost przystań marina port", "id": "dermaga pelabuhan tambatan kapal marina jeti",
             "ja": "埠頭 波止場 桟橋 岸壁 マリーナ 港", "zh_CN": "码头 船坞 栈桥 突堤 游艇码头 港口",
             "zh_TW": "碼頭 埠頭 碼頭岸 邊碼頭 遊艇碼頭 港口 港灣"},
    "water": {"en": "water body waterbody surface water pond basin wetland flood lake river stream reservoir",
              "fr": "eau plan d'eau etendue d'eau mare bassin zone humide lac riviere etang",
              "es": "agua cuerpo de agua masa de agua estanque humedal lago rio",
              "pt": "agua corpo dagua massa de agua lagoa acude lago rio",
              "de": "gewässer wasserfläche teich becken feuchtgebiet see fluss bach reservoir",
              "it": "acqua specchio d acqua bacino stagno lago fiume torrente",
              "nl": "water wateroppervlak waterlichaam vijver bekken moeras meer rivier beek reservoir",
              "pl": "woda zbiornik wodny akwen staw jezioro rzeka potok mokradło",
              "id": "badan air permukaan air kolam danau sungai waduk rawa", "ja": "水域 水面 池 湿地 湖 河川 貯水池",
              "zh_CN": "水体 水面 湖泊 河流 水塘 湿地 水库", "zh_TW": "水域 水體 水面 池塘 湖泊 河流 濕地"},
    "bare_ground": {"en": "bare soil dirt sand cleared land earth", "fr": "terre nue sable terrain nu remblai",
                    "es": "tierra desnuda arena terreno despejado", "pt": "solo nu areia terreno limpo",
                    "de": "blanker boden erde sand gerodete fläche freifläche",
                    "it": "terreno nudo suolo sabbia terra area sgombra",
                    "nl": "kale grond braakliggende grond zandgrond bouwterrein aarde",
                    "pl": "goła ziemia odkryta gleba piasek teren oczyszczony grunt",
                    "id": "tanah terbuka tanah kosong pasir lahan terbuka bumi", "ja": "裸地 土壌 土地 砂地 更地 地面",
                    "zh_CN": "裸地 裸土 泥土 沙地 清理地块 地面", "zh_TW": "裸地 裸土 泥地 沙地 清理地 地表 土地"},
    "rock": {"en": "rocks stone boulder outcrop bedrock rocky", "fr": "roches pierre rocher affleurement rocheux",
             "es": "rocas piedra canto rodado afloramiento rocoso", "pt": "rochas pedra pedregulho afloramento rochoso",
             "de": "felsen stein felsbrocken felsvorsprung grundgestein felsig",
             "it": "roccia pietra masso affioramento roccioso roccia madre",
             "nl": "rots rotsen steen kei rotswand gesteente",
             "pl": "skały kamień głaz wychodnia skalna podłoże skaliste",
             "id": "batu bebatuan bongkah singkapan batuan dasar berbatu", "ja": "岩 石 岩塊 露岩 基盤岩 岩場",
             "zh_CN": "岩石 石块 巨石 岩层 裸岩 岩质地面", "zh_TW": "岩石 石塊 巨石 岩層 基岩 岩質地面"},
    "quarry": {"en": "mine pit gravel pit open pit extraction", "fr": "mine graviere carriere extraction",
               "es": "mina gravera cantera", "pt": "mina cascalheira mineracao",
               "de": "steinbruch grube kiesgrube tagebau abbaugebiet",
               "it": "cava miniera fossa cava di ghiaia miniera a cielo aperto",
               "nl": "groeve mijn dagbouw grindgroeve steengroeve afgraving",
               "pl": "kamieniołom kopalnia wyrobisko żwirownia odkrywka",
               "id": "tambang galian tambang terbuka lubang tambang kerikil",
               "ja": "採石場 鉱山 掘削場 砂利採取場 露天掘り", "zh_CN": "采石场 矿坑 砂石坑 露天矿 开采区",
               "zh_TW": "採石場 礦坑 砂石坑 露天礦坑 採掘場"},
    "car": {"en": "vehicle auto automobile cars van", "fr": "vehicule voitures automobile camionnette",
            "es": "vehiculo automovil autos furgoneta", "pt": "veiculo automovel carros van",
            "de": "auto fahrzeug pkw wagen transporter", "it": "auto automobile vettura veicolo macchina",
            "nl": "auto voertuig personenauto wagen bestelbus", "pl": "samochód auto pojazd samochody furgonetka",
            "id": "mobil kendaraan otomobil van", "ja": "車 自動車 乗用車 車両 バン",
            "zh_CN": "汽车 轿车 小汽车 车辆 面包车", "zh_TW": "汽車 車輛 小客車 轎車 廂型車"},
    "truck": {"en": "lorry semi hgv freight van", "fr": "poids lourd semi-remorque fourgon",
              "es": "camiones trailer furgon", "pt": "caminhoes carreta furgao",
              "de": "lastwagen lkw sattelschlepper schwerlastwagen lieferwagen",
              "it": "camion autocarro tir autotreno furgone", "nl": "vrachtwagen truck trekker oplegger bestelwagen",
              "pl": "ciężarówka tir samochód ciężarowy zestaw ciężarowy furgon",
              "id": "truk lori kendaraan angkutan trailer van", "ja": "トラック 貨物車 大型車 トレーラー ローリー",
              "zh_CN": "卡车 货车 重型卡车 半挂车 厢式货车", "zh_TW": "卡車 貨車 拖車 大型貨車 運輸車"},
    "train": {"en": "railcar wagon locomotive rolling stock", "fr": "wagon locomotive rame",
              "es": "vagon locomotora tren", "pt": "vagao locomotiva composicao",
              "de": "zug triebwagen waggon lokomotive schienenfahrzeug",
              "it": "treno locomotiva vagone carrozza convoglio ferroviario",
              "nl": "trein treinstel wagon locomotief rollend materieel",
              "pl": "pociąg wagon lokomotywa skład kolejowy tabor kolejowy",
              "id": "kereta gerbong lokomotif rangkaian kereta", "ja": "列車 鉄道車両 貨車 機関車 車両",
              "zh_CN": "火车 列车 轨道车 机车 车厢", "zh_TW": "火車 列車 鐵路車廂 機車 鐵道車輛"},
    "farm_field": {"en": "field cropland farmland parcel crop agriculture",
                   "fr": "champ parcelle culture terre agricole", "es": "campo cultivo parcela agricultura",
                   "pt": "campo lavoura cultura agricultura",
                   "de": "feld ackerland landwirtschaftsfläche flurstück anbaufläche agrarfläche",
                   "it": "campo agricolo terreno coltivato particella agricola coltura agricoltura",
                   "nl": "akker landbouwgrond boerenland perceel gewas landbouw",
                   "pl": "pole uprawne grunty rolne działka rolna uprawa rolnictwo",
                   "id": "lahan pertanian sawah ladang kebun tanaman", "ja": "農地 畑 耕地 圃場 作付地 農業地",
                   "zh_CN": "农田 耕地 农场地块 作物田 农业用地", "zh_TW": "農田 農地 耕地 田區 作物地 農業用地"},
    "field": {"en": "fields cropland farmland parcel plot paddock crop", "fr": "champs parcelle culture terrain lopin",
              "es": "campos parcela cultivo terreno lote", "pt": "campos talhao parcela cultivo terreno lote",
              "de": "felder ackerland landwirtschaftsfläche parzelle weidefläche anbaufläche",
              "it": "campo campi terreno agricolo appezzamento parcella pascolo coltura",
              "nl": "velden akker landbouwgrond perceel kavel weiland gewas",
              "pl": "pola pole uprawne grunty rolne parcela działka pastwisko uprawa",
              "id": "lapangan lahan pertanian ladang petak lahan padang", "ja": "畑 耕地 農地 圃場 区画 放牧地",
              "zh_CN": "田地 耕地 农田 地块 地块区 牧场 作物田", "zh_TW": "田地 農田 耕地 農地 地塊 園地 牧場"},
    "vineyard": {"en": "vines grapes wine", "fr": "vignoble vignes parcelle viticole", "es": "vina vinedo parras",
                 "pt": "vinha parreiral uva", "de": "weinreben weinberg rebfläche traubenanbau",
                 "it": "vigneto vigna uve vitigni coltivazione della vite",
                 "nl": "wijngaard wijnstokken druiven wijnbouw",
                 "pl": "winnica winorośl winogrona plantacja winorośli uprawa winorośli",
                 "id": "kebun anggur tanaman anggur perkebunan anggur",
                 "ja": "ブドウ畑 葡萄園 ぶどう園 果樹園 ワイン畑", "zh_CN": "葡萄园 葡萄田 葡萄种植园 葡萄藤",
                 "zh_TW": "葡萄園 葡萄田 葡萄種植地 葡萄藤 酒莊葡萄園"},
    "solar_panel": {"en": "pv photovoltaic solar module rooftop solar solar farm solar park",
                    "fr": "photovoltaique pv module solaire centrale solaire",
                    "es": "fotovoltaico pv placa solar modulo parque solar",
                    "pt": "fotovoltaico pv placa solar modulo usina solar",
                    "de": "solarmodul photovoltaik pv solaranlage dachsolar solarpark",
                    "it": "pannello solare fotovoltaico modulo fotovoltaico impianto solare parco fotovoltaico",
                    "nl": "zonnepaneel zonnepanelen pv fotovoltaïsch zonnepark zonnedak",
                    "pl": "panel fotowoltaiczny fotowoltaika panel słoneczny farma fotowoltaiczna park solarny",
                    "id": "panel surya fotovoltaik modul surya pembangkit surya",
                    "ja": "太陽光パネル 太陽電池 パネル ソーラーパネル メガソーラー",
                    "zh_CN": "太阳能板 光伏板 光伏组件 屋顶光伏 光伏电站 太阳能农场",
                    "zh_TW": "太陽能板 光電板 太陽能模組 屋頂太陽能 太陽能農場 光電場"},
    "wind_turbine": {"en": "windmill wind farm turbine wind power", "fr": "aerogenerateur parc eolien moulin",
                     "es": "eolico molino parque eolico", "pt": "eolica cata-vento parque eolico",
                     "de": "windrad windkraftanlage windpark turbine windenergieanlage",
                     "it": "turbina eolica aerogeneratore pala eolica parco eolico energia eolica",
                     "nl": "windturbine windmolen windpark turbine windenergie",
                     "pl": "turbina wiatrowa wiatrak elektrownia wiatrowa farma wiatrowa park wiatrowy",
                     "id": "turbin angin kincir angin ladang angin pembangkit angin",
                     "ja": "風力発電機 風車 風力タービン 風力発電所 ウィンドファーム",
                     "zh_CN": "风力机 风车 风力涡轮机 风电机组 风电场",
                     "zh_TW": "風力發電機 風車 風力機 風場 風力發電"},
    "swimming_pool": {"en": "pool pools swimming water", "fr": "piscines bassin eau", "es": "alberca pileta piscinas",
                      "pt": "piscinas tanque", "de": "schwimmbecken pool schwimmbad wasserbecken",
                      "it": "piscina piscine vasca nuoto acqua", "nl": "zwembad zwembaden zwemwater bad",
                      "pl": "basen pływalnia kąpielisko basen ogrodowy zbiornik kąpielowy",
                      "id": "kolam renang kolam berenang kolam air",
                      "ja": "プール 水泳場 スイミングプール 屋外プール 水場", "zh_CN": "游泳池 泳池 水池 戏水池",
                      "zh_TW": "游泳池 水池 泳池 戲水池"},
    "tennis_court": {"en": "tennis court padel", "fr": "tennis terrain padel", "es": "tenis cancha padel",
                     "pt": "tenis quadra padel", "de": "tennisplatz tennisfeld padelplatz",
                     "it": "campo da tennis padel campo da padel", "nl": "tennisbaan tennisveld padelbaan",
                     "pl": "kort tenisowy kort padel boisko tenisowe",
                     "id": "lapangan tenis lapangan padel arena tenis",
                     "ja": "テニスコート パデルコート テニス場 球技場", "zh_CN": "网球场 网球场地 板式网球场",
                     "zh_TW": "網球場 網球場地 壁球場 帕德爾球場"},
    "soccer_field": {"en": "football pitch sports field", "fr": "football terrain de sport foot",
                     "es": "futbol cancha campo deportivo", "pt": "futebol campo quadra",
                     "de": "fußballplatz sportplatz spielfeld rasenplatz",
                     "it": "campo da calcio campo sportivo terreno di gioco calcio",
                     "nl": "voetbalveld sportveld voetbalterrein",
                     "pl": "boisko piłkarskie boisko do piłki nożnej stadion sportowy murawa",
                     "id": "lapangan sepak bola lapangan olahraga arena bola",
                     "ja": "サッカー場 フットボール場 運動場 スポーツグラウンド",
                     "zh_CN": "足球场 球场 运动场 足球场地",
                     "zh_TW": "足球場 踢足球場 運動場 球場 草地球場"},
    "running_track": {"en": "athletics track oval", "fr": "athletisme piste stade", "es": "atletismo pista tartan",
                      "pt": "atletismo pista tartan", "de": "laufbahn leichtathletikbahn tartanbahn ovalbahn",
                      "it": "pista di atletica pista da corsa ovale atletica",
                      "nl": "atletiekbaan atletiekpiste sintelbaan ovaalbaan",
                      "pl": "bieżnia lekkoatletyczna tor biegowy stadion lekkoatletyczny owal",
                      "id": "lintasan lari trek atletik lintasan oval",
                      "ja": "陸上トラック 競技トラック トラック 楕円形トラック",
                      "zh_CN": "跑道 田径场 椭圆跑道 田径跑道", "zh_TW": "田徑場 跑道 環形跑道 田徑跑道"},
    "stadium": {"en": "arena sports ground grandstand", "fr": "arene enceinte sportive tribune",
                "es": "arena gradas coliseo", "pt": "arena arquibancada",
                "de": "stadion arena sportstätte tribüne sportplatz",
                "it": "stadio arena impianto sportivo tribuna campo sportivo",
                "nl": "stadion arena sportterrein tribune sportcomplex",
                "pl": "stadion arena obiekt sportowy trybuny boisko sportowe",
                "id": "stadion arena olahraga lapangan utama tribun",
                "ja": "スタジアム 競技場 アリーナ グラウンド 観客席", "zh_CN": "体育场 体育馆 竞技场 看台 运动场",
                "zh_TW": "體育場 運動場 體育館 看台場地 競技場"},
    "airplane": {"en": "plane aircraft jet aviation", "fr": "avions aeronef jet aviation", "es": "aviones aeronave jet",
                 "pt": "avioes aeronave jato", "de": "flugzeug flieger passagierflugzeug jet luftfahrzeug",
                 "it": "aereo aeroplano velivolo jet aeromobile", "nl": "vliegtuig toestel jet luchtvaart",
                 "pl": "samolot statek powietrzny odrzutowiec lotnictwo",
                 "id": "pesawat pesawat terbang jet penerbangan", "ja": "飛行機 航空機 ジェット機 航空機体 航空",
                 "zh_CN": "飞机 客机 喷气机 航空器", "zh_TW": "飛機 航空器 客機 噴射機 航空"},
    "boat": {"en": "vessel yacht dinghy sailboat canoe ship cargo ship",
             "fr": "barque voilier yacht embarcation navire cargo", "es": "barca velero lancha yate buque",
             "pt": "lancha veleiro canoa navio", "de": "boot schiff yacht segelboot kanu frachter",
             "it": "barca imbarcazione yacht gommone barca a vela canoa nave mercantile",
             "nl": "boot vaartuig jacht sloep zeilboot kano schip vrachtschip",
             "pl": "łódź jacht kajak żaglówka statek barka", "id": "kapal perahu yacht kano kapal kargo",
             "ja": "船 ボート ヨット カヌー 貨物船 帆船", "zh_CN": "船只 船艇 游艇 小船 帆船 独木舟 货船",
             "zh_TW": "船隻 船艇 遊艇 小艇 帆船 獨木舟 貨船"},
    "construction_site": {"en": "building site works excavation earthworks", "fr": "chantiers travaux terrassement",
                          "es": "obras construccion movimiento de tierras", "pt": "obras canteiro terraplenagem",
                          "de": "baustelle bauplatz erdaushub erdbau bauarbeiten",
                          "it": "cantiere edile lavori scavo sbancamento area di costruzione",
                          "nl": "bouwplaats bouwterrein bouwwerf graafwerk grondwerk",
                          "pl": "plac budowy budowa wykop roboty ziemne teren budowy",
                          "id": "lokasi konstruksi proyek bangunan penggalian pekerjaan tanah",
                          "ja": "建設現場 工事現場 建築現場 掘削現場 土木工事",
                          "zh_CN": "施工现场 建筑工地 工地 挖掘区 土方工程",
                          "zh_TW": "工地 建築工地 施工現場 挖掘場 土方工程"},
    "crane": {"en": "tower crane gantry port crane", "fr": "grues portique", "es": "gruas portico",
              "pt": "guindastes portico", "de": "kran turmdrehkran portalkran hafenkran",
              "it": "gru gru a torre gru a portale gru portuale",
              "nl": "kraan torenkraan hijskraan havenkraan portaalkraan",
              "pl": "żuraw dźwig żuraw wieżowy suwnica dźwig portowy",
              "id": "derek crane derek menara derek pelabuhan gantry",
              "ja": "クレーン タワークレーン 門型クレーン 港湾クレーン 起重機", "zh_CN": "起重机 塔吊 龙门吊 港口吊机",
              "zh_TW": "起重機 塔式起重機 龍門吊 港口起重機 吊車"},
    "shipping_container": {"en": "container containers freight intermodal", "fr": "conteneurs container caisse",
                           "es": "contenedores contenedor maritimo", "pt": "conteineres container",
                           "de": "container seecontainer frachtcontainer transportcontainer wechselbehälter",
                           "it": "container containers cassone merci unità intermodale",
                           "nl": "container containers vrachtcontainer zeecontainer transportcontainer",
                           "pl": "kontener kontenery kontener transportowy kontener morski ładunek intermodalny",
                           "id": "kontainer peti kemas wadah kargo angkutan",
                           "ja": "コンテナ 貨物コンテナ 輸送コンテナ 海上コンテナ ISOコンテナ",
                           "zh_CN": "集装箱 货柜 运输箱 联运箱", "zh_TW": "貨櫃 集裝箱 貨櫃箱 運輸箱 聯運貨櫃"},
    "lawn": {"en": "turf sward mown grass garden lawn amenity grass",
             "fr": "pelouse gazon herbe tondue espace vert terrain engazonné",
             "es": "césped pasto hierba jardín pradera", "pt": "grama gramado relvado jardim área verde",
             "de": "rasen grünfläche gemähte wiese gartenrasen zierrasen",
             "it": "prato tappeto erboso erba tagliata giardino prato ornamentale area verde",
             "nl": "gazon grasmat grasveld gemaaid gras tuin gazonstrook",
             "pl": "trawnik murawa skoszona trawa ogród trawnik ozdobny teren zielony",
             "id": "rumput halaman rumput taman rumput potong hamparan rumput", "ja": "芝生 芝 草地 刈草 庭芝 公園芝",
             "zh_CN": "草坪 草地 修剪草地 庭院草坪 公共绿地", "zh_TW": "草皮 草坪 草地 修剪草地 庭園草坪 休憩草地"},
    "hedge": {"en": "hedgerow shrub row hedge line boundary hedge windbreak",
              "fr": "haie brise vent haie arbustive alignement arbustes clôture végétale",
              "es": "seto cercado arbustos lindero cortavientos",
              "pt": "cerca viva sebe fileira arbustos divisa quebra vento",
              "de": "hecke heckenreihe strauchreihe grenzhecke windschutzhecke",
              "it": "siepe filare arbusti barriera siepe divisoria frangivento",
              "nl": "haag heg heggen struikenrij haaglijn erfafscheiding windsingel",
              "pl": "żywopłot szpaler krzewów granica żywopłotowa pas zarośli wiatrochron",
              "id": "pagar tanaman semak berbaris batas tanaman penahan angin",
              "ja": "生垣 垣根 低木列 植え込み 境界樹 防風林", "zh_CN": "树篱 灌木篱 篱笆绿篱 绿篱带 边界绿篱 防风林带",
              "zh_TW": "樹籬 灌木籬 樹籬線 邊界樹籬 防風林帶 綠籬"},
    "orchard": {"en": "fruit trees plantation grove tree rows apple orchard",
                "fr": "verger arbres fruitiers plantation bosquet rangées arbres pommeraie",
                "es": "frutales plantación huerto arboleda manzanos",
                "pt": "pomar árvores frutíferas plantação bosque fileiras árvores",
                "de": "obstgarten obstplantage baumgruppe baumreihen apfelplantage",
                "it": "frutteto alberi da frutto piantagione filare di alberi meleti filari",
                "nl": "boomgaard fruitbomen plantage boomgroep bomenrijen appelboomgaard",
                "pl": "sad drzewa owocowe plantacja gaj rzędy drzew sad jabłoniowy",
                "id": "kebun buah perkebunan pohon buah rumpun barisan pohon",
                "ja": "果樹園 果樹農園 樹木園 果樹列 りんご園", "zh_CN": "果园 果树园 植物园 林地 果树行 苹果园",
                "zh_TW": "果園 果樹園 果樹種植地 林園 果樹列 蘋果園"},
    "crop_field": {"en": "cropland arable field crop parcel cultivated field farmland",
                   "fr": "cultures champ agricole parcelle cultivée terres agricoles zone cultivée",
                   "es": "cultivo parcela agrícola campo sembrado terreno labrado",
                   "pt": "lavoura campo cultivo área agrícola terreno cultivado plantação",
                   "de": "ackerland acker feld anbaufläche bewirtschaftete fläche landwirtschaftsfläche",
                   "it": "terreno coltivato campo arabile coltura particella agricola seminativo azienda agricola",
                   "nl": "akker bouwland landbouwperceel gewasakker cultuurland landbouwgrond",
                   "pl": "pole uprawne grunty orne uprawa działka rolna ziemia uprawna gospodarstwo rolne",
                   "id": "lahan tanaman lahan pertanian ladang budidaya petak sawah",
                   "ja": "耕地 畑 作物畑 圃場 農地 田畑", "zh_CN": "农田 耕地 作物田 种植地 农业地块 旱田",
                   "zh_TW": "農田 耕地 旱田 作物田 地塊 耕作地 農地"},
    "soil": {"en": "earth dirt topsoil ground bare earth terrain",
             "fr": "sol terre terre végétale terrain sol nu terre nue", "es": "tierra suelo terreno terrón mantillo",
             "pt": "solo terra terra vegetal subsolo terreno solo exposto",
             "de": "erde boden oberboden grund blanke erde gelände",
             "it": "suolo terra terriccio terreno nudo superficie terrestre",
             "nl": "grond aarde teelaarde bodem kale grond terrein",
             "pl": "gleba ziemia grunt humus podłoże goła ziemia teren",
             "id": "tanah bumi tanah humus permukaan tanah lahan kosong", "ja": "土 土壌 表土 地面 裸地 地形",
             "zh_CN": "土壤 泥土 表土 地面 裸土 地形", "zh_TW": "土壤 泥土 表土 地面 裸土 地形 裸露土地"},
    "stone": {"en": "stones boulder rubble rocky block masonry", "fr": "pierres rocher gravats rocheux bloc maçonnerie",
              "es": "piedras rocas pedruscos escombros bloques mampostería",
              "pt": "pedras pedregulho cascalho rocha bloco alvenaria",
              "de": "steine felsbrocken geröll felsig baustein mauerwerk",
              "it": "pietre masso detriti roccia blocco muratura", "nl": "stenen kei puin rotsachtig blok metselwerk",
              "pl": "kamienie głaz gruz rumowisko skalne blok kamienny mur",
              "id": "batu bebatuan bongkah puing batu tembok", "ja": "石 岩石 岩塊 がれき 石材 石積み",
              "zh_CN": "石头 石块 巨石 碎石 岩石 砌石", "zh_TW": "石頭 巨石 碎石 岩石 石塊 石材砌體"},
    "pond": {"en": "small lake basin waterhole farm pond retention basin",
             "fr": "étang mare bassin plan d'eau retenue réserve", "es": "estanque laguna charca depósito balsa",
             "pt": "lagoa açude tanque bacia reservatório espelho agua",
             "de": "teich kleiner see wasserbecken wasserloch hofteich rückhaltebecken",
             "it": "stagno laghetto bacino pozza d acqua laghetto agricolo bacino di raccolta",
             "nl": "vijver meertje bekken waterpoel boerderijvijver retentiebekken",
             "pl": "staw małe jezioro zbiornik wodny oczko wodne staw retencyjny zbiornik gospodarczy",
             "id": "kolam danau kecil embung kolam retensi waduk kecil",
             "ja": "池 小湖 水溜まり 貯水池 農業用池 調整池", "zh_CN": "池塘 小湖 水塘 水洼 农场池塘 蓄水池",
             "zh_TW": "池塘 小湖 水池 水坑 農塘 滯洪池"},
    "river": {"en": "stream watercourse creek channel waterway",
              "fr": "rivière fleuve cours d'eau ruisseau canal chenal",
              "es": "río arroyo riachuelo cauce canal corriente", "pt": "rio córrego riacho canal curso agua arroio",
              "de": "bach fließgewässer wasserlauf kanal wasserweg flussbett",
              "it": "fiume torrente corso d acqua canale alveo via d acqua",
              "nl": "rivier beek waterloop kreek kanaal watergang",
              "pl": "rzeka strumień ciek wodny potok kanał koryto wodne droga wodna",
              "id": "sungai anak sungai aliran air kanal saluran air", "ja": "川 河川 小川 水路 渓流 河道",
              "zh_CN": "河流 溪流 河道 水道 沟渠 水路", "zh_TW": "溪流 河道 小溪 水道 河渠 水路"},
    "roof": {"en": "roofs roof surface house roof building roof shingles",
             "fr": "toiture toit couverture toit de maison toit de bâtiment tuiles",
             "es": "tejado cubierta techumbre azotea tejas",
             "pt": "telhado cobertura laje telhas teto cobertura predial",
             "de": "dächer dachfläche hausdach gebäudedach dachziegel",
             "it": "tetto tetti copertura tetto di casa tegole copertura edificio",
             "nl": "daken dakoppervlak huisdak gebou dak dakpannen",
             "pl": "dach dachy powierzchnia dachu dach domu dach budynku gonty",
             "id": "atap permukaan atap genteng atap rumah atap bangunan",
             "ja": "屋根 屋根面 家屋根 建物屋根 瓦屋根 屋根材", "zh_CN": "屋顶 房顶 屋面 屋顶表面 房屋屋顶 建筑屋顶",
             "zh_TW": "屋頂 房頂 屋面 建築屋頂 瓦片屋頂 屋頂表面"},
    "driveway": {"en": "drive access road private road entrance car access",
                 "fr": "allée accès route privée entrée carrossable chemin privé",
                 "es": "entrada acceso camino cochera vial privado",
                 "pt": "entrada garagem acesso veicular caminho pavimentado via acesso",
                 "de": "zufahrt auffahrt private straße einfahrt autozufahrt",
                 "it": "vialetto accesso carrabile strada privata ingresso auto accesso veicolare",
                 "nl": "oprit toegangsweg privéweg ingang auto oprit",
                 "pl": "podjazd droga dojazdowa droga prywatna wjazd dojazd samochodowy",
                 "id": "jalan masuk akses kendaraan jalan pribadi pintu masuk",
                 "ja": "私道 車道 進入路 車庫道 出入口 車両アクセス", "zh_CN": "车道 进出道路 私家路 入口车道 车辆通道",
                 "zh_TW": "車道 進出道路 私人道路 車道入口 汽車通道"},
    "taxiway": {"en": "apron airport taxi lane aircraft taxiway airfield",
                "fr": "voie de circulation aire de trafic voie taxi piste de roulage taxiway aérodrome",
                "es": "rodaje plataforma calle aeronaves pista aeropuerto",
                "pt": "pista taxi pista rolamento taxiway pátio aeronaves área aeroporto",
                "de": "rollbahn vorfeld flughafen rollweg flugplatz rollstraße",
                "it": "raccordo pista di rullaggio piazzale aeroporto corsia di rullaggio campo aeroportuale",
                "nl": "taxibaan platform luchthaven taxistrook vliegtuigbaan vliegveld",
                "pl": "droga kołowania płyta lotniskowa lotnisko pas kołowania droga dla samolotów",
                "id": "jalur taxi pesawat taxiway apron bandara lapangan terbang",
                "ja": "誘導路 エプロン 空港誘導路 滑走路連絡路 飛行場",
                "zh_CN": "滑行道 停机坪 机场滑行道 飞机滑行道 机场跑道",
                "zh_TW": "滑行道 停機坪 機場滑行道 飛機滑行道 機場道路"},
    "water_tower": {"en": "watertower elevated tank water tank standpipe",
                    "fr": "château d'eau réservoir surélevé citerne surélevée réservoir aérien",
                    "es": "depósito torre aljibe tanque elevado tinaco",
                    "pt": "torre d'água caixa d'água reservatório elevado castelo d'água",
                    "de": "wasserturm hochbehälter wasserhochbehälter tankturm standrohr",
                    "it": "torre dell acqua serbatoio sopraelevato cisterna idrica torre piezometrica acquedotto",
                    "nl": "watertoren verhoogde tank waterreservoir standpijp",
                    "pl": "wieża ciśnień zbiornik wieżowy zbiornik wodny hydrofornia stojący zbiornik",
                    "id": "menara air tangki air tandon air tangki tinggi",
                    "ja": "給水塔 水塔 高架水槽 貯水タンク スタンドパイプ",
                    "zh_CN": "水塔 高架水箱 储水塔 水罐塔 立式水塔", "zh_TW": "水塔 高架水槽 儲水塔 水槽塔 立式水塔"},
}


def preset_search_terms(pid: str) -> dict[str, str]:
    """The extra search words for one preset, empty when it has none."""
    return dict(_SEARCH_TERMS.get(pid) or {})
